default: &default
  adapter: postgresql
  encoding: unicode
  schema_search_path: "blog_content, public"
  pool: 5
  host: localhost
  username: publify_core
  password:

development:
  <<: *default
  database: publify_core_development

test:
  <<: *default
  database: publify_core_test

